/**
 * N60: `materializeMarkerPatch()` -- the overlay as a git patch against the
 * spec repository (E11.3).
 *
 * The overlay (S2) feeds two consumers: the local applier (N1), which marks
 * a copy of the corpus under `ir/.build/`, and this function, which emits
 * the same insertions as a unified diff whose paths are relative to the
 * spec repository root (`docs/...`). The patch is the payload of the bulk
 * marker PR (U30); a subset of IDs is the payload of the proof-of-concept
 * PR (U29). Once either merges, the provisions it covers no longer need
 * overlay entries: the extractor reads the marked text from the submodule
 * directly (E3.3).
 *
 * A marker never contains a newline, so a marked file has exactly the
 * lines of the unmarked one and every change is a one-line replacement.
 * That keeps the diff builder small: changed lines, grouped into hunks
 * with three lines of context, in the format `git apply` reads.
 */
import type { Corpus } from "../corpus.ts";
import { markText, type ResolvedSpan } from "./overlay.ts";

export interface MarkerPatch {
  patch: string;
  /** Corpus files the patch touches, in patch order. */
  files: string[];
  /** Provisions whose markers the patch inserts. */
  provisions: string[];
}

const CONTEXT = 3;

/** Emit the marker insertions for `spans` (all, or only the IDs in `only`) as a unified diff against the spec repository. */
export function materializeMarkerPatch(corpus: Corpus, spans: ResolvedSpan[], read: (file: string) => string, only: ReadonlySet<string> | null = null): MarkerPatch {
  const selected = only === null ? spans : spans.filter((s) => only.has(s.id));
  if (only !== null) {
    const known = new Set(spans.map((s) => s.id));
    for (const id of only) if (!known.has(id)) throw new Error(`markers patch: ${id} is not in the overlay`);
  }
  const bySource = new Map<string, ResolvedSpan[]>();
  for (const span of selected) bySource.set(span.source, [...(bySource.get(span.source) ?? []), span]);
  const files = corpus.files.filter((f) => bySource.has(f));
  const header = [
    `# Provision markers for ACS ${corpus.version ?? "unknown"}${corpus.commit ? ` at ${corpus.commit}` : ""}.`,
    `# Generated by \`acs-ir markers patch\` from ir/markers/overlay.yaml; ${selected.length} provision(s) across ${files.length} file(s).`,
    `# Apply from the spec repository root with \`git apply\`.`,
    "",
  ].join("\n");
  const body = files.map((file) => fileDiff(`docs/${file}`, read(file), markText(read(file), bySource.get(file) ?? []))).join("");
  return { patch: header + body, files, provisions: selected.map((s) => s.id).sort() };
}

/** One file's unified diff, for texts with the same number of lines (a marked file adds no line breaks). */
export function fileDiff(path: string, before: string, after: string): string {
  const oldLines = splitLines(before);
  const newLines = splitLines(after);
  if (oldLines.length !== newLines.length) throw new Error(`${path}: marked text has ${newLines.length} lines, unmarked has ${oldLines.length}; a marker must not contain a line break`);
  const changed: number[] = [];
  for (let i = 0; i < oldLines.length; i++) if (oldLines[i] !== newLines[i]) changed.push(i);
  if (changed.length === 0) return "";
  const noNewline = !before.endsWith("\n");

  const hunks: { start: number; end: number }[] = [];
  for (const i of changed) {
    const last = hunks[hunks.length - 1];
    const start = Math.max(0, i - CONTEXT);
    const end = Math.min(oldLines.length, i + CONTEXT + 1);
    if (last && start <= last.end) last.end = end;
    else hunks.push({ start, end });
  }

  const out: string[] = [`diff --git a/${path} b/${path}`, `--- a/${path}`, `+++ b/${path}`];
  const changedSet = new Set(changed);
  for (const hunk of hunks) {
    const count = hunk.end - hunk.start;
    out.push(`@@ -${hunk.start + 1},${count} +${hunk.start + 1},${count} @@`);
    let i = hunk.start;
    while (i < hunk.end) {
      if (!changedSet.has(i)) {
        out.push(` ${oldLines[i]}`);
        i++;
        continue;
      }
      // A run of consecutive changed lines: all removals, then all additions.
      let j = i;
      while (j < hunk.end && changedSet.has(j)) j++;
      for (let k = i; k < j; k++) out.push(`-${oldLines[k]}`, ...(noNewline && k === oldLines.length - 1 ? ["\\ No newline at end of file"] : []));
      for (let k = i; k < j; k++) out.push(`+${newLines[k]}`, ...(noNewline && k === newLines.length - 1 ? ["\\ No newline at end of file"] : []));
      i = j;
    }
    if (noNewline && hunk.end === oldLines.length && !changedSet.has(oldLines.length - 1)) out.push("\\ No newline at end of file");
  }
  return out.join("\n") + "\n";
}

function splitLines(text: string): string[] {
  const lines = text.split("\n");
  if (text.endsWith("\n")) lines.pop();
  return lines;
}
