/**
 * N10: `runCensus()` -- source census, provision census, S11.
 *
 * `ir/census/sources.yaml` is authored and read here; `ir/census/provisions.yaml`
 * is generated and written here, and nowhere else. A generated file that
 * disagrees with a fresh run is a CI failure (`--check`), for the same
 * reason E4.2 gives for the manifest: the committed copy exists so a
 * reviewer can read the diff, and a stale copy is a diff nobody read.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { loadCorpus, readSource, type Corpus } from "../corpus.ts";
import { defaultMarkersDir, parseOverlay, resolveOverlay } from "../markers/overlay.ts";
import { parseExclusions, resolveExclusions, type ResolvedExclusion } from "./exclusions.ts";
import { toYaml, type YamlValue } from "../yaml.ts";
import { provisionCensus, type ProvisionCensus } from "./provision-census.ts";
import { parseSourceDeclarations, sourceCensus, type SourceCensus } from "./source-census.ts";

export interface CensusRun {
  corpus: Corpus;
  sources: SourceCensus;
  /** Absent when the source census has problems: a provision census over an undeclared corpus would be a count with no declared basis. */
  provisions: ProvisionCensus | null;
  /** The generated file's content, as it would be written. */
  yaml: string | null;
}

export function defaultCensusDir(): string {
  return resolve(import.meta.dir, "..", "..", "census");
}

export function runCensus(options: { corpusRoot?: string; sourcesFile?: string; overlayFile?: string | null; exclusionsFile?: string | null } = {}): CensusRun {
  const corpus = loadCorpus(options.corpusRoot);
  const sourcesFile = options.sourcesFile ?? join(defaultCensusDir(), "sources.yaml");
  const declared = parseSourceDeclarations(readFileSync(sourcesFile, "utf8"));
  const sources = sourceCensus(declared, corpus.files);

  // The overlay is optional input: absent, nothing is bound. Present and
  // unresolvable, the census fails alongside the source census rather than
  // reporting bound and unbound counts based on an unresolved overlay.
  const overlayFile = options.overlayFile === undefined ? join(defaultMarkersDir(), "overlay.yaml") : options.overlayFile;
  let spans: ReturnType<typeof resolveOverlay>["spans"] = [];
  if (overlayFile !== null && existsSync(overlayFile)) {
    const resolution = resolveOverlay(parseOverlay(readFileSync(overlayFile, "utf8")), (file) =>
      corpus.files.includes(file) ? readSource(corpus, file) : null,
    );
    sources.problems.push(...resolution.problems.map((p) => `overlay: ${p}`));
    spans = resolution.spans;
  }
  // Exclusions live beside the source declaration they refine, so a test
  // corpus with its own sources.yaml never picks up the real catalog's.
  const exclusionsFile = options.exclusionsFile === undefined ? join(dirname(sourcesFile), "exclusions.yaml") : options.exclusionsFile;
  let exclusions: ResolvedExclusion[] = [];
  if (exclusionsFile !== null && existsSync(exclusionsFile)) {
    const resolved = resolveExclusions(parseExclusions(readFileSync(exclusionsFile, "utf8")), (file) =>
      corpus.files.includes(file) ? readSource(corpus, file) : null,
    );
    sources.problems.push(...resolved.problems);
    exclusions = resolved.exclusions;
  }
  if (sources.problems.length > 0) return { corpus, sources, provisions: null, yaml: null };

  const provisions = provisionCensus(corpus, declared, (file) => readSource(corpus, file), spans, exclusions);
  sources.problems.push(...provisions.exclusion_problems);
  if (provisions.exclusion_problems.length > 0) return { corpus, sources, provisions: null, yaml: null };
  return { corpus, sources, provisions, yaml: renderYaml(provisions) };
}

const HEADER = [
  "# GENERATED by `acs-ir census` -- do not edit.",
  "# The provision census: every RFC 2119 keyword occurrence in the declared",
  "# corpus and what became of it. Regenerate with `bun run ir census`; CI runs",
  "# `bun run ir census --check` and fails when this file is stale.",
  "",
].join("\n");

export function renderYaml(census: ProvisionCensus): string {
  return HEADER + toYaml(census as unknown as YamlValue);
}
