/**
 * N33: `emitTlaInvariants()` -- the declared protocol-invariant list (S15, R6.2).
 *
 * The TLA+ model is a later work stream; nothing in V1 to V8 reads this.
 * It exists so the model checks a declared list rather than an ad-hoc one:
 * every Invariant in the catalog, with its ID, its text, and the
 * Requirements that enforce it, as a module skeleton whose operators are
 * left for the modeller to fill.
 */
import type { CatalogEntry } from "../catalog/catalog.ts";

export function emitTlaInvariants(entries: CatalogEntry[], corpus: { version: string | null; commit: string | null }): string {
  const invariants = entries.filter((e) => e.manifest.type === "Invariant");
  const out = [
    "---- MODULE AcsInvariants ----",
    `\\* GENERATED by \`acs-ir compile\`. ACS ${corpus.version ?? "?"} at ${corpus.commit?.slice(0, 7) ?? "unknown"}.`,
    "\\* The declared protocol invariants (R6.2). Each operator is a placeholder the model fills;",
    "\\* the IDs are the catalog's and never change (R2.2).",
    "",
  ];
  for (const inv of invariants) {
    const enforcers = entries.filter((e) => e.record.depends_on.includes(inv.manifest.id)).map((e) => e.manifest.id);
    out.push(`\\* ${inv.manifest.id}: ${inv.record.title}`);
    for (const line of inv.manifest.text.split("\n")) out.push(`\\*   ${line}`);
    if (enforcers.length) out.push(`\\*   enforced by: ${enforcers.join(", ")}`);
    out.push(`${inv.manifest.id.replace(/-/g, "_")} == TRUE \\* to be modelled`, "");
  }
  out.push(`Invariants == ${invariants.length ? invariants.map((i) => i.manifest.id.replace(/-/g, "_")).join(" /\\ ") : "TRUE"}`, "", "====");
  return out.join("\n") + "\n";
}
