/**
 * N34: `emitSouffleProgram()` -- the published `.dl` (S8, E7.3).
 *
 * A deliverable, not a build temp: an auditor runs it with stock Soufflé
 * 2.5 over a directory of `.facts` files and gets one CSV per compiled
 * provision, without this repository's TypeScript. The program declares
 * each column domain as a subtype of `symbol` or `number`, so Soufflé's
 * own type checker refuses a rule that joins a `seq` to a `bound`. Every
 * non-static vocabulary relation is an `.input`; static relations carry
 * their tuples inline as facts; each compiled provision contributes its
 * helpers and its violation relation, which is an `.output` with typed
 * columns (subject columns, then witness columns). The differential oracle
 * reads those outputs back and compares them with the evaluator's (R3.8).
 */
import type { CompiledProvision, RuleProgram } from "./compile.ts";
import { formatTerm, type Literal, type Rule, type Term } from "./predicate.ts";
import { domainTypeName, type Column, type Relation } from "./vocabulary.ts";

export function emitSouffleProgram(program: RuleProgram): string {
  const out: string[] = [
    "// GENERATED by `acs-ir compile` from ir/provisions/*.yaml over ir/vocabulary/relations.yaml. Do not edit.",
    `// ACS ${program.corpus.version ?? "?"} at ${program.corpus.commit?.slice(0, 7) ?? "unknown"}.`,
    "// Run: souffle -F <facts dir> -D <out dir> rules.dl   (Soufflé 2.5; facts are tab-separated, one file per relation;",
    "//      the out dir receives one tab-separated <provision>__violation.csv per compiled provision)",
    "",
    "// ---- column domains: a value's kind, as a subtype, so a seq is never joined to a bound ----",
  ];
  for (const d of program.domains) out.push(`.type ${domainTypeName(d.name)} <: ${d.type}`);
  out.push("", "// ---- fact vocabulary ----");
  for (const rel of program.relations) {
    out.push(`.decl ${rel.name}(${columns(rel.columns)})`);
    if (rel.source === "static") {
      for (const tuple of rel.facts) out.push(`${rel.name}(${tuple.map((v) => (typeof v === "number" ? String(v) : JSON.stringify(v))).join(", ")}).`);
    } else {
      out.push(`.input ${rel.name}(IO=file, filename="${rel.name}.facts", delimiter="\\t")`);
    }
  }
  out.push("", "// ---- violations: subject columns, then witness columns; one .output per provision ----");
  for (const p of program.provisions) {
    out.push("", `// ${p.id}: ${p.status}${p.reason ? ` -- ${p.reason}` : ""}${p.alias_of ? ` (${p.alias_of})` : ""}`);
    if (p.status !== "compiled" || !p.violation) continue;
    out.push(...emitProvision(p));
  }
  return out.join("\n") + "\n";
}

function emitProvision(p: CompiledProvision): string[] {
  const out: string[] = [];
  for (const h of p.helpers) out.push(`.decl ${h.name}(${columns(h.columns)})`);
  const v = p.violation as NonNullable<CompiledProvision["violation"]>;
  out.push(`.decl ${v.name}(${columns(v.columns)})`, `.output ${v.name}`);
  for (const rule of p.rules) out.push(`// ${rule.source}`, emitRule(rule));
  return out;
}

function columns(cols: Column[]): string {
  return cols.map((c) => `${c.name}:${c.domain ? domainTypeName(c.domain) : c.type}`).join(", ");
}

function emitRule(rule: Rule): string {
  return `${atom(rule.head.relation, rule.head.args)} :- ${rule.body.map(literal).join(", ")}.`;
}

function atom(relation: string, args: Term[]): string {
  return `${relation}(${args.map(term).join(", ")})`;
}

function literal(lit: Literal): string {
  switch (lit.kind) {
    case "atom":
      return `${lit.negated ? "!" : ""}${atom(lit.atom.relation, lit.atom.args)}`;
    case "cmp":
      return `${term(lit.left)} ${lit.op} ${term(lit.right)}`;
    case "count":
      return `${lit.target} = count : { ${lit.atoms.map((a) => atom(a.relation, a.args)).join(", ")} }`;
  }
}

/** Soufflé's `cat` takes two arguments, so an n-ary cat nests. */
function term(t: Term): string {
  if (t.kind === "func" && t.name === "cat") {
    const parts = t.args.map(term);
    return parts.slice(1).reduce((acc, part) => `cat(${acc}, ${part})`, parts[0] ?? '""');
  }
  if (t.kind === "func") return `${t.name}(${t.args.map(term).join(", ")})`;
  return formatTerm(t);
}

export type { Relation };
