/**
 * N34: `emitSouffleProgram()` -- the published `.dl` (S8, E7.3).
 *
 * A deliverable, not a build temp: an auditor runs it with stock Soufflé
 * 2.5 over a directory of `.facts` files and gets `violation.csv`, without
 * this repository's TypeScript. Every non-static vocabulary relation is an
 * `.input`; static relations carry their tuples inline; each compiled
 * provision contributes its helpers, its violation relation, and a rule
 * into the one unified `violation(provision, subject, witness)` output
 * that the differential oracle compares (R3.8).
 */
import type { CompiledProvision, RuleProgram } from "./compile.ts";
import { formatTerm, type Literal, type Rule, type Term } from "./predicate.ts";
import type { Column, Relation } from "./vocabulary.ts";

export function emitSouffleProgram(program: RuleProgram): string {
  const out: string[] = [
    "// GENERATED by `acs-ir compile` from ir/provisions/*.yaml over ir/vocabulary/relations.yaml. Do not edit.",
    `// ACS ${program.corpus.version ?? "?"} at ${program.corpus.commit?.slice(0, 7) ?? "unknown"}.`,
    "// Run: souffle -F <facts dir> -D <out dir> rules.dl   (Soufflé 2.5; facts are tab-separated, one file per relation)",
    "",
    "// ---- fact vocabulary (S7) ----",
  ];
  for (const rel of program.relations) {
    out.push(`.decl ${rel.name}(${columns(rel.columns)})`);
    if (rel.source === "static") {
      for (const tuple of rel.facts) out.push(`${rel.name}(${tuple.map((v) => (typeof v === "number" ? String(v) : JSON.stringify(v))).join(", ")}).`);
    } else {
      out.push(`.input ${rel.name}(IO=file, filename="${rel.name}.facts", delimiter="\\t")`);
    }
  }
  out.push("", "// ---- violations (R3.4: subject columns, then witness columns) ----", ".decl violation(provision:symbol, subject:symbol, witness:symbol)", '.output violation(IO=file, filename="violation.csv", delimiter="\\t")');
  for (const p of program.provisions) {
    out.push("", `// ${p.id}: ${p.status}${p.reason ? ` -- ${p.reason}` : ""}${p.alias_of ? ` (${p.alias_of})` : ""}`);
    if (p.status !== "compiled" || !p.violation) continue;
    out.push(...emitProvision(p));
  }
  return out.join("\n") + "\n";
}

function emitProvision(p: CompiledProvision): string[] {
  const out: string[] = [];
  for (const h of p.helpers) out.push(`.decl ${h.name}(${columns(h.columns)})`);
  const v = p.violation as NonNullable<CompiledProvision["violation"]>;
  out.push(`.decl ${v.name}(${columns(v.columns)})`);
  for (const rule of p.rules) out.push(`// ${rule.source}`, emitRule(rule));
  const vars = v.columns.map((_, i) => `V${i}`);
  const subject = joined(vars.slice(0, p.subject.length), v.columns.slice(0, p.subject.length));
  const witness = joined(vars.slice(p.subject.length), v.columns.slice(p.subject.length));
  out.push(`violation(${JSON.stringify(p.id)}, ${subject}, ${witness}) :- ${v.name}(${vars.join(", ")}).`);
  return out;
}

/** `cat` is binary in Soufflé; the unified columns join values with "|", numbers through to_string. */
function joined(vars: string[], cols: Column[]): string {
  const parts = vars.map((v, i) => (cols[i]?.type === "number" ? `to_string(${v})` : v));
  return parts.slice(1).reduce((acc, part) => `cat(cat(${acc}, "|"), ${part})`, parts[0] ?? '""');
}

function columns(cols: Column[]): string {
  return cols.map((c) => `${c.name}:${c.type}`).join(", ");
}

function emitRule(rule: Rule): string {
  return `${atom(rule.head.relation, rule.head.args)} :- ${rule.body.map(literal).join(", ")}.`;
}

function atom(relation: string, args: Term[]): string {
  return `${relation}(${args.map(term).join(", ")})`;
}

function literal(lit: Literal): string {
  switch (lit.kind) {
    case "atom":
      return `${lit.negated ? "!" : ""}${atom(lit.atom.relation, lit.atom.args)}`;
    case "cmp":
      return `${term(lit.left)} ${lit.op} ${term(lit.right)}`;
    case "count":
      return `${lit.target} = count : { ${lit.atoms.map((a) => atom(a.relation, a.args)).join(", ")} }`;
  }
}

/** Soufflé's `cat` takes two arguments, so an n-ary cat nests. */
function term(t: Term): string {
  if (t.kind === "func" && t.name === "cat") {
    const parts = t.args.map(term);
    return parts.slice(1).reduce((acc, part) => `cat(${acc}, ${part})`, parts[0] ?? '""');
  }
  if (t.kind === "func") return `${t.name}(${t.args.map(term).join(", ")})`;
  return formatTerm(t);
}

export type { Relation };
