/**
 * N50: `renderProvisionIndex()` -- P2, the human-readable catalog.
 *
 * U12 the index, U13 per-provision detail with the deep link the marker
 * will publish (U26), and U14 the test-coverage table from the citation
 * index over `ir/test/conformance/` (R6.3).
 */
import { effectiveKeyword, type Catalog, type CatalogEntry } from "../catalog/catalog.ts";
import { idToAnchor } from "../ids.ts";

export function renderProvisionIndex(catalog: Catalog, corpus: { version: string | null; commit: string | null }, citations: Map<string, string[]> = new Map()): string {
  const out: string[] = [];
  out.push(
    "<!-- GENERATED by `acs-ir render` from ir/manifest/provisions.json and ir/provisions/*.yaml. Do not edit. -->",
    "",
    `# ACS provision index`,
    "",
    `ACS ${corpus.version ?? "?"} at \`${corpus.commit?.slice(0, 7) ?? "unknown"}\`. ${catalog.entries.length} provisions.`,
    "",
    "## Index",
    "",
    ...table(
      ["ID", "Type", "Keyword", "Actor", "Profile", "Evidence", "Modality", "Status", "Source", "Title"],
      catalog.entries.map(({ manifest: m, record: r }) => [
        `[${m.id}](#${m.id.toLowerCase()})`,
        m.type,
        (m.type === "Requirement" ? effectiveKeyword(m, r) : m.level) ?? "—",
        r.actor,
        r.profile === "all" ? "all" : r.profile.join(", "),
        r.evidence_class,
        r.modality_kind,
        r.status,
        `${m.source_file}:${m.line}`,
        r.title,
      ]),
    ),
    "",
    "## Provisions",
    "",
  );
  for (const entry of catalog.entries) out.push(...renderDetail(entry), "");
  const untested = catalog.entries.filter(({ manifest: m }) => !citations.get(m.id)?.length).length;
  out.push(
    "## Test coverage",
    "",
    `${catalog.entries.length - untested} of ${catalog.entries.length} provisions are cited by a conformance test or fixture under \`ir/test/conformance/\`.`,
    "",
    ...table(["ID", "Conformance tests"], catalog.entries.map(({ manifest: m }) => [m.id, citations.get(m.id)?.join(", ") ?? "none"])),
  );
  return out.join("\n") + "\n";
}

function renderDetail({ manifest: m, record: r }: CatalogEntry): string[] {
  const lines = [
    `### ${m.id}`,
    "",
    `**${r.title}.** ${m.type}${m.level ? `, ${m.level}` : ""}. \`${m.source_file}:${m.line}\` (${m.block_type}${m.section_slug ? `, §\`${m.section_slug}\`` : ""}). Anchor: \`#${idToAnchor(m.id)}\`.`,
    "",
    ...m.text.split("\n").map((l) => `> ${l}`),
    "",
    `- Actor: ${r.actor}; reported against: ${r.reported_against}`,
    `- Profile: ${r.profile === "all" ? "all" : r.profile.join(", ")}${r.activation ? `; activation: ${r.activation}` : ""}`,
    `- Modality: ${r.modality_kind}; evidence: ${r.evidence_class}${m.type === "Requirement" ? `; keyword: ${effectiveKeyword(m, r) ?? "none"}` : ""}`,
  ];
  if (r.keyword) lines.push(`- Keyword ${r.keyword} stated by the record, not the span (${m.level ?? "no keyword"}): ${r.keyword_basis}`);
  if (r.schema_refs.length) lines.push(`- Schema: ${r.schema_refs.map((s) => `\`${s.file}#${s.pointer}\``).join(", ")}`);
  if (r.depends_on.length) lines.push(`- Depends on: ${r.depends_on.map(link).join(", ")}`);
  if (r.restates) lines.push(`- Restates: ${link(r.restates)}`);
  if (r.superseded_by.length) lines.push(`- Superseded by: ${r.superseded_by.map(link).join(", ")}`);
  lines.push(`- Status: ${r.status}, since ${r.since}; reviewed against \`${r.reviewed_against.slice(0, 12)}\`${r.reviewed_against === m.text_hash ? "" : " (**stale**: text changed)"}`);
  if (r.note) lines.push(`- Note: ${r.note}`);
  return lines;
}

function link(id: string): string {
  return `[${id}](#${id.toLowerCase()})`;
}

function table(header: string[], rows: string[][]): string[] {
  const line = (cells: string[]): string => `| ${cells.map((c) => c.replace(/\|/g, "\\|").replace(/\n/g, " ")).join(" | ")} |`;
  return [line(header), `|${header.map(() => "---").join("|")}|`, ...rows.map(line)];
}
